GET https://nestjstypescriptstarterpractic-onjn--3000--858c0e43.local-credentialless.webcontainer.io/tasks

###

POST https://nestjstypescriptstarterpractic-onjn--3000--858c0e43.local-credentialless.webcontainer.io/tasks
content-type: application/json

{
    "name": "Jazmin"
}

GET https://nestjstypescriptstarterpractic-onjn--3000--858c0e43.local-credentialless.webcontainer.io/tasks?id/a
